<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPFskpG6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPFskpG6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPFskpG6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPFskpG6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPFskpG6\App_KernelDevDebugContainer([
    'container.build_hash' => 'PFskpG6',
    'container.build_id' => '7351a2e7',
    'container.build_time' => 1720943669,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPFskpG6');
